#!/bin/bash

# INIT VARIABLES
MODELESDIR="/path/to/ezinit_full/models" # chemin vers le dossiers des models
MODELEVH=$MODELESDIR"ez_generic_vhost" # generic vhost
MODELEMYSQL=$MODELESDIR"ez_generic_initdb.sql" # generic database create mysql
EZSOURCE="/path/to/ezpublish.zip" # instance ezpublish vierge (zip ou dossier)
WORKPATH="/tmp" # dossier pour créer des fichiers temporaires 
WEBPATH="/var/www" # chemin des projets web (par default /var/www)
ADRESSEIP="127.0.0.1" # adresse IP pour le site (normalement 127.0.0.1)
MYSQLUSR="user" # connexion à mysql : user et pswd
MYSQLPSWD="password"
